export const metadata = {
  title: 'Gabriel Dama Tournament',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-new-gr-c-s-check-loaded="14.1103.0" data-gr-ext-installed="">
        {children}
      </body>
    </html>
  )
}
